[build]
  command = "CI='' npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "https://sankohtech.com/*"
  to = "https://www.sankohtech.com/:splat"
  status = 301
  force = true

  [build.environment]
  ESLINT_NO_DEV_ERRORS = "true"